### ISSUE TITLE
trailing slash missing in Top Navbar

### ISSUE THREAD

**Issue by ckleemann** [d120/mailman-theme#1]
To view the archive of a list a trailing slash is required after the Listname. This slash is missing in the Top Navbar.
For example on the fs:
"Nachrichtenarchive" links to https://www.fachschaft.informatik.tu-darmstadt.de/mailman/private/fs
But it has to link to https://www.fachschaft.informatik.tu-darmstadt.de/mailman/private/fs/

Without the slash the archive is not working. The login procedure adds the slash automatic but if the user is already logged in the archive is not working.

**Comment by luelista** [comment]
Fixed :)
